---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tribuan2/public_html
    - cd /home/tribuan2/repositories/tribuana-admin-panel
    - /bin/rsync -avz --exclude=".git" --exclude="vendor" --exclude="node_modules" ./ $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - cd $DEPLOYPATH
    - /opt/cpanel/ea-php82/root/usr/bin/php artisan config:cache
    - /opt/cpanel/ea-php82/root/usr/bin/php artisan route:cache
    - /opt/cpanel/ea-php82/root/usr/bin/php artisan view:cache
