---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tribuan2/public_html
    - /bin/rsync -avz --exclude=".git" --exclude="node_modules" --exclude="vendor" ./ $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - cd $DEPLOYPATH
    - /opt/cpanel/ea-php82/root/usr/bin/php artisan config:cache
    - /opt/cpanel/ea-php82/root/usr/bin/php artisan route:cache
    - /opt/cpanel/ea-php82/root/usr/bin/php artisan view:cache
